# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: studentrentalaggregator
open_collective: student-rental-aggregator
ko_fi: studentrentalaggregator
liberapay: student-rental-aggregator
issuehunt: # Replace with your username
otechie: # Replace with your username
custom: ['https://www.buymeacoffee.com/studentrental']
